[project]
name = "car-plates-numbers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "filterpy==1.4.5",
    "flask>=3.1.0",
    "lap>=0.5.12",
    "ncnn>=1.0.20250503",
    "numpy>=2.0.2",
    "opencv-python",
    "paddleocr",
    "paddlepaddle>=3.0.0",
    "scikit-image>=0.24.0",
    "setuptools>=80.4.0",
    "ultralytics",
]

[tool.uv]
exclude-newer = "2025-05-13T02:07:43Z"

[tool.uv.extra-build-dependencies]
scikit-image = ["numpy", "distutils.msvccompiler"]

